from .contracts import MethodContext, MethodResult, MethodSpec
from ..ideas import generate_idea_batch
from ..llm_parser import generate_ideas_with_openai


def local_idea_query(context: MethodContext) -> MethodResult:
    ideas = generate_idea_batch(context.project_dir, context.interest, context.idea_count)
    return MethodResult(
        status="pass" if ideas else "review",
        message=f"{len(ideas)} idea(s) generated by the local query method.",
        details={
            "idea_count": len(ideas),
            "top_score": ideas[0]["feasibility_score"] if ideas else 0,
        },
    )


def gpt_review_ready_query(context: MethodContext) -> MethodResult:
    ideas = generate_idea_batch(context.project_dir, context.interest, context.idea_count)
    for idea in ideas:
        idea["review_status"] = "gpt_review_ready"
    return MethodResult(
        status="review",
        message=f"{len(ideas)} idea(s) generated and marked for GPT/human review.",
        details={"idea_count": len(ideas), "requires_review": True},
    )


def gpt_idea_query(context: MethodContext) -> MethodResult:
    try:
        seed_ideas = generate_ideas_with_openai(context.interest, context.idea_count)
        ideas = generate_idea_batch(context.project_dir, context.interest, context.idea_count, seed_ideas=seed_ideas)
        return MethodResult(
            status="review",
            message=f"{len(ideas)} idea(s) generated by GPT and scored locally.",
            details={"idea_count": len(ideas), "requires_review": True, "source": "openai"},
        )
    except Exception as exc:
        ideas = generate_idea_batch(context.project_dir, context.interest, context.idea_count)
        return MethodResult(
            status="review",
            message=f"GPT idea generation unavailable; used local fallback. Reason: {exc}",
            details={"idea_count": len(ideas), "requires_review": True, "source": "local_fallback", "error": str(exc)},
        )


METHODS = [
    MethodSpec(
        method_id="local_idea_query_v0",
        stage="query",
        label="Local idea query v0",
        description="Deterministic local idea generation using existing TargetCompass templates and data fit.",
        runner=local_idea_query,
    ),
    MethodSpec(
        method_id="gpt_review_ready_query_v0",
        stage="query",
        label="GPT review-ready query v0",
        description="Keeps local generation but marks the batch for GPT or human skill review before execution.",
        runner=gpt_review_ready_query,
        gpt_compatible=True,
    ),
    MethodSpec(
        method_id="gpt_idea_query_v0",
        stage="query",
        label="GPT idea query v0",
        description="Uses OpenAI to generate idea candidates, then scores them with local feasibility rules; falls back locally if unavailable.",
        runner=gpt_idea_query,
        gpt_compatible=True,
    ),
]
